### ISSUE TITLE
Nightly triggers Windows Defender

### ISSUE THREAD

**Issue by asampal** [arturo-lang/nightly#2]
Tried to unzip the full nightly (arturo-0.9.77-2021-06-24-Windows-full.zip) and Defender removed the executable.

![image](https://user-images.githubusercontent.com/281639/123202725-2286dc80-d483-11eb-8f93-a7e3f5772e8c.png)

**Comment by drkameleon** [comment]
I don't know how I missed this issue for sooo long, but I guess I did. Sorry!

Does the issue persist? And, if so, which Windows version are we talking about?

(I don't have any Windows machine available, but if there are still issues like that - either with the nightly, or most importantly with the main releases - I'll have to find out what goes wrong and why it mistakenly identifies the binary as a... trojan 😮 )

Thanks a lot for mentioning it! 👍

**Comment by asampal** [comment]
The build you created last night didn't seem to trigger anything on Windows 11, so no longer an issue for me.
